### ISSUE TITLE
Cannot start thrught entry point

### ISSUE THREAD

**Issue by Shin-nn** [ikogan/docker-openmediavault#2]
Hi, I am trying to run this docker image, but I always end with: 
`/usr/sbin/omv-startup: line 39: config.section.data: command not found`
I run image as:
`docker run --name OpenMediaVault -ti -h openmediavault.example.test -P ikogan/openmediavault`

Am I doing something wrong?
Thanks!

**Comment by Shin-nn** [comment]
Sorry, my bad, fist you have to create container.ini.

**Comment by ikogan** [comment]
While you did figure out the workaround, I've pushed a change that allows you to omit the container.ini or individual entries from it in https://github.com/ikogan/docker-openmediavault/commit/6d3de93b2b2c3505654648844426481e8832361d.

New images have been pushed.

**Comment by Shin-nn** [comment]
Cool! Thanks!
