### ISSUE TITLE
Problem for Fake Shared Folders

### ISSUE THREAD

**Issue by hsucw** [ikogan/docker-openmediavault#3]
Hi, 
I want to install the image on my WIN 10, and I want to configure the fake shared folder as your suggestion. But I notice that there is no  `omv_config_add_element` command in the container. Is there any plugin I did not install? Thanks for your help.

**Comment by ikogan** [comment]
Whoops, thanks, I forgot to add a line to source the "helper-functions" bash library included with OpenMediaVault. It's located in `/usr/share/openmediavault/scripts/helper-functions` and contains all of the `omv_*` functions you're looking for.

**Comment by thewilli** [comment]
@ikogan just found this closed issue. Did you maybe forget to add this to the README, as I still cannot find any reference to these helper functions?

**Comment by ikogan** [comment]
It was apparently only done in the dev branch.
