### ISSUE TITLE
 Failed to get filesystems

### ISSUE THREAD

**Issue by DmitryNefedov** [ikogan/docker-openmediavault#5]
Hi,
thanks for your work.

I'm trying to make it work and having some issues. Any help will be appreciated.

I currently have desktop (E7500, 4Gb RAM, 2HDD - 150Gb sda and 1Tb sdb) with Ubuntu 16.04 and latest docker. sdb neither mounted nor used by ubuntu.
I used command with some changes to  it - exposes port 80 and makes sdb accessable from container.
`sudo docker run --name OpenMediaVault -d -ti -h openmediavault.example.test -p 3000:80 -v /data:/data:Z --cap-add SYS_ADMIN --device /dev/sdb:/dev/sdb:rw -P ikogan/openmediavault`

As a result, i can access omv and sdb device is recognised by the system.
Storage -> Physical Disks show hdd properly; however,when i try to access Storage -> File systems it gives an error "Failed to get filesystems"
`
Error #6000:
exception 'OMVException' with message 'Failed to get filesystems' in /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc:77
Stack trace:
#0 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array)
#1 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(317): OMVRpcServiceAbstract->callMethod('enumerateFilesy...', NULL, Array)
#3 [internal function]: OMVRpcServiceFileSystemMgmt->getList(Array, Array)
#4 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#5 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('getList', Array, Array)
#6 /usr/sbin/omv-engined(500): OMVRpc::exec('FileSystemMgmt', 'getList', Array, Array, 1)
#7 {main}
`

I have checked /etc/fstab and its empty
`# UNCONFIGURED FSTAB FOR BASE SYSTEM`

Moreover, trying to mount hdd gives an error
`root@openmediavault:/#  sudo mount -t ntfs /dev/sdb1 /media`
`mount: block device /dev/sdb is write-protected, mounting read-only`
`mount: cannot mount block device /dev/sdb read-only`

I can mount and access it with no issue in host system.

What am i missing? what steps should be followed to fix it?

**Comment by ikogan** [comment]
According to the docs for `--device`, it looks like you might want to remove the `:rw` from your device argument as it's missing the `m` flag, which means it's not able to `mknod` the device. The default is `:rwm` which is likely what you want.

**Comment by ZhouzlCHN** [comment]
Hi,
I used command 
docker run --name omv -d -p 80:80 -v /data --device /dev/sda2:/dev/sda ikogan/openmediavault
and do not have this error.

**Comment by MrDach** [comment]
I'm seeing the same error. My command looks like this:
`docker run --name omv -itd --device /dev/sda -p 8080:80 -v /home/dc/omv:/data -P ikogan/openmediavault`.

Running lsblk on my host machine returns the following:

`NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0   5,5T  0 disk 
nvme0n1     259:0    0 223,6G  0 disk 
├─nvme0n1p1 259:1    0   300M  0 part /boot/efi
└─nvme0n1p2 259:2    0 223,3G  0 part /`

I'm running Lubuntu 19.04.

@DmitryNefedov did you ever figure out what the issue was?
