### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by kmh020** [ikogan/docker-openmediavault#8]
I'm tring on ubuntu16.04

In my case,I can't login with my ubuntu's ccount and root either. 

My docker command is below

docker run --name OpenMediaVault -d -ti -p 8090:80 -p 8443:443 -v /hdd/omv/data:/data:Z -P ikogan/openmediavault

Could you give any advice to solve the issue ?

**Comment by ikogan** [comment]
Hi, I'm assuming you mean login to the web interface? If so, the answer is here: https://wiki.openmediavault.org/index.php?title=Installation.

The default user is "admin" and the default password is "openmediavault". You should be careful though as these container images were built with a very old version of OpenMediaVault and have not been updated.

**Comment by kmh020** [comment]
Thanks you  ~!
